[versions]
kotlin = "2.2.21"

[libraries]

th2-bom = { group = "com.exactpro.th2", name = "bom", version = "4.14.3" }
th2-common = { group = "com.exactpro.th2", name = "common", version = "5.17.2-dev" }
th2-grpc-common = { group = "com.exactpro.th2", name = "grpc-common", version = "4.7.5" }
th2-common-utils = { group = "com.exactpro.th2", name = "common-utils", version = "2.4.0-dev" }

kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging", version = "7.0.14" }

junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version = "5.14.3" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version = "6.2.3" }
strikt-core = { group = "io.strikt", name = "strikt-core", version = "0.34.1" }

[plugins]
th2-publish = { id = "com.exactpro.th2.gradle.publish", version = "0.3.14" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }